FROM node:22-alpine AS build
ARG VITE_TRAVELAGENCY_BACKEND_SERVER
ARG VITE_TRAVELAGENCY_BACKEND_PORT
ARG VITE_TRAVELAGENCY_KEYCLOAK_SERVER
ARG VITE_TRAVELAGENCY_KEYCLOAK_PORT

ENV VITE_TRAVELAGENCY_BACKEND_SERVER=$VITE_TRAVELAGENCY_BACKEND_SERVER
ENV VITE_TRAVELAGENCY_BACKEND_PORT=$VITE_TRAVELAGENCY_BACKEND_PORT
ENV VITE_TRAVELAGENCY_KEYCLOAK_SERVER=$VITE_TRAVELAGENCY_KEYCLOAK_SERVER
ENV VITE_TRAVELAGENCY_KEYCLOAK_PORT=$VITE_TRAVELAGENCY_KEYCLOAK_PORT
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]