services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tingeso
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8021:8021"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/tingeso
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      frontend:
        build: .
        ports:
          - "5173:5173"
        depends_on:
          - backend
      #jenkins:
      #image: jenkins/jenkins:lts
      #container_name: jenkins-server
      #privileged: true
      #user: root
      #ports:
      # - "8080:8080"
      #- "50000:50000"
      #volumes:
      # - jenkins_data:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      #restart: always

volumes:
  postgres_data: #jenkins_data:
